name: farid
favicon: null
layout_spectrum: 0.8588516828604043
typography_spectrum: 0.1371068365406245
title: Kids Pics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.15325342887081206
  lightness: 0.02738284505903721
  saturation: 0.6002177724149078
  rhythmicContrast: 0.6940888604149222
purpose: []
